# Generated by Django 4.2.8 on 2024-02-11 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='../qpbpxmxgezgshlrkwmhb', upload_to='images/'),
        ),
    ]
